### ISSUE TITLE
Как взаимодействовать со Stateful виджетами из WidgetModel

### ISSUE THREAD

**Issue by alexander-shustanov** [surfstudio/mwwm#3]
Добрый день!

В примере я видел, что вы допускаете передачу стейта виджета в конструктор WidgetModel (например NavigatorState). Но как быть со stateful виджетами созданными внутри WidgetState, например виджет Form? На момент создания WidgetModel метод build еще не отработал, в лучшем случае мы можем передать в WidgetState тот же GlobalKey, с которым потом создадим Form. 

Пример иерархии:

```
class SomeScreen extends CoreMwwmWidget {
   ...
}

class SomeScreenState extends WidgetState<SomeScreenWm> {
    Widget build(BuildContext context) {
        return Form(
                ...
                Button(onTap: () => wm.submit()),
        );
    }
}

class SomeScreenWm extends WidgetModel {
    void submit() {
        if(form.validate()) {
        ....
        } else {
        }
  
    }
}
```

Я думаю такая проблема присуща любому виджету, который допускает императивное взаимодействие со своим состоянием.

**Comment by r3tam** [comment]
Да, вы правильно предлагаете: передавать GlobalKey. Когда это необходимо. Например, мы так (на данный момент) работаем со Scaffold.

**Comment by r3tam** [comment]
Извините за долгий ответ, если вдруг будут еще вопросы: рекомендую завести их в https://github.com/surfstudio/SurfGear
